# Generated by Django 2.2.16 on 2021-08-29 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0009_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="author",
        ),
        migrations.AddField(
            model_name="follow",
            name="author",
            field=models.ManyToManyField(
                help_text="Впишите имя автора",
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
