# Generated by Django 2.2.16 on 2021-08-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0012_auto_20210829_1959"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="author",
        ),
        migrations.AddField(
            model_name="follow",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Впишите имя автора",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
