# Generated by Django 2.2.16 on 2021-08-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_auto_20210829_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Впишите имя автора",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
